### ISSUE TITLE
Is there anyway to add value tags to the webhook?

### ISSUE THREAD

**Issue by EricAndrechek** [tobimori/streamdeck-ifttt#3]
I want to add this to my Stream Deck so that when I press it, it saves the song currently playing to my library. To do this I need at the very least the song title, but the artist's name is a good idea to include. I read the code and it's sending the request without any of the values attached. Are there any plans to add the feature?

**Comment by tobimori** [comment]
Value tags are unnecessary for this plugin. If I'd add them, you could only enter one song, you could not dynamically change them to the current playing song. (Which you can already do on IFTTT, you don't need to use Webhooks for static value tags) This is due to the plugins infrastructure, it's written in javascript and therefore has no information about your computer. Another way would be using the Spotify API. This would probably work, but remove the original easy-to-use but limited use case.
I don't use Spotify, but If you want you can try using BarRaiders Spotify plugin. It's directly connected to the API, so that should make things easier, but I don't know If it supports saving a song.
